module.exports = [
  {
    files: ['**/*.js'],
    ignores: ['node_modules/**', 'dist/**', 'vite.config.js', '*.test.js', 'sw.js', 'layer-tests.js'],
    languageOptions: {
      ecmaVersion: 'latest',
      sourceType: 'script',
      globals: {
        window: 'readonly',
        document: 'readonly',
        console: 'readonly',
        setTimeout: 'readonly',
        setInterval: 'readonly',
        clearTimeout: 'readonly',
        clearInterval: 'readonly',
        requestAnimationFrame: 'readonly',
        URL: 'readonly',
        Blob: 'readonly',
        Image: 'readonly',
        FileReader: 'readonly',
        FormData: 'readonly',
        fetch: 'readonly',
        TextEncoder: 'readonly',
        TextDecoder: 'readonly',
        Intl: 'readonly',
        Array: 'readonly',
        Math: 'readonly',
        Date: 'readonly',
        JSON: 'readonly',
        Object: 'readonly',
        String: 'readonly',
        Number: 'readonly',
        Boolean: 'readonly',
        RegExp: 'readonly',
        Map: 'readonly',
        Set: 'readonly',
        Promise: 'readonly',
        Symbol: 'readonly',
        WeakMap: 'readonly',
        WeakSet: 'readonly',
        Error: 'readonly',
        TypeError: 'readonly',
        RangeError: 'readonly',
        Uint8Array: 'readonly',
        Uint16Array: 'readonly',
        Uint32Array: 'readonly',
        Float32Array: 'readonly',
        Float64Array: 'readonly',
        ArrayBuffer: 'readonly',
        SharedArrayBuffer: 'readonly',
        DataView: 'readonly',
        Event: 'readonly',
        CustomEvent: 'readonly',
        HTMLElement: 'readonly',
        HTMLCanvasElement: 'readonly',
        CanvasRenderingContext2D: 'readonly',
        HTMLTextAreaElement: 'readonly',
        HTMLSelectElement: 'readonly',
        HTMLInputElement: 'readonly',
        HTMLDivElement: 'readonly',
        HTMLButtonElement: 'readonly',
        HTMLSpanElement: 'readonly',
        HTMLHeadingElement: 'readonly',
        HTMLLabelElement: 'readonly',
        HTMLImageElement: 'readonly',
        HTMLLinkElement: 'readonly',
        MutationObserver: 'readonly',
        IntersectionObserver: 'readonly',
        ResizeObserver: 'readonly',
        performance: 'readonly',
        requestIdleCallback: 'readonly',
        cancelAnimationFrame: 'readonly',
        crypto: 'readonly',
        alert: 'readonly',
        confirm: 'readonly',
        prompt: 'readonly',
        navigator: 'readonly',
        location: 'readonly',
        history: 'readonly',
        localStorage: 'readonly',
        sessionStorage: 'readonly',
        indexedDB: 'readonly',
        // Project globals (declared in code, not true globals)
        // S, pages, isAnimating, cursiveConnector, getDiagramImage, PAGE_W, PAGE_H
        // are declared in index.js and used by other modules via window.*
        PDFDocument: 'readonly',
        jsPDF: 'readonly',
        mermaid: 'readonly',
        Rough: 'readonly',
        ot: 'readonly',
        mammoth: 'readonly',
        tf: 'readonly',
        FontFace: 'readonly',
        OffscreenCanvas: 'readonly',
        MediaRecorder: 'readonly',
        AudioContext: 'readonly',
        webkitAudioContext: 'readonly',
        SpeechRecognition: 'readonly',
        webkitSpeechRecognition: 'readonly',
        ClipboardItem: 'readonly',
        showDirectoryPicker: 'readonly',
        FileSystemHandle: 'readonly',
        // Module globals
        module: 'readonly',
        require: 'readonly',
        exports: 'writable',
        __dirname: 'readonly',
        __filename: 'readonly',
        WebSocket: 'readonly',
        Path2D: 'readonly',
        DOMParser: 'readonly',
        CursiveConnector: 'readonly',
        MarkdownParser: 'readonly',
        FontSwitcher: 'readonly',
        StrokePredictionEngine: 'readonly',
        DiagramEngine: 'readonly',
        ScriptDetector: 'readonly',
        FontCompilation: 'readonly',
        PaperRenderer: 'readonly',
        TextLayout: 'readonly',
        ExportRenderers: 'readonly',
        templateManager: 'readonly',
        layerCompositor: 'readonly',
        collaborativeEngine: 'readonly',
        contextualJitterEngine: 'readonly',
        strokePredictionEngine: 'readonly',
        toggleAudioRecording: 'readonly',
        renderSpecificPage: 'readonly',
        undoSketchStroke: 'readonly',
        updateBrushSize: 'readonly',
        clearSketchCanvas: 'readonly',
        pageObserver: 'readonly',
        currentRenderQueue: 'readonly',
        currentRcCache: 'readonly',
        _rcCache: 'readonly',
        rough: 'readonly',
        cursiveConnector: 'readonly',
        getDiagramImage: 'readonly',
        initLayerCompositor: 'readonly',
        positionDiagramNodes: 'readonly',
        getCharVariation: 'readonly',
        CharacterVariationContext: 'readonly',
        getCharVariationWithContext: 'readonly',
        renderCursiveConnections: 'readonly',
        CollaborativeEngine: 'readonly',
        drawStudioCanvas: 'readonly',
        screen: 'readonly',
        PAGE_W: 'readonly',
        PAGE_H: 'readonly',
        S: 'readonly',
      },
    },
    rules: {
      'no-unused-vars': [
        'warn',
        {
          argsIgnorePattern: '^_',
          varsIgnorePattern:
            '^(pageTexts|pageCount|queue|toggleSection|triggerRender|clearText|insertDiagramTemplate|autoFitFontSize|setTextAlignment|resetToDefaults|toggleCollaboration|setPaper|addNewLayer|flattenAllLayers|setInkPreset|toggleAudioRecording|aiAction|exportImage|exportTransparentPNG|exportPDF|exportSVG|copyToClipboard|startAnimation|stopAnimation|navigatePage|closeHandFontedModal|switchFontTab|switchSheet|undoSketchStroke|clearSketchCanvas|saveActiveCharacter|advanceActiveCharacter|exportFontProject|generateDownloadTemplate|buildCustomFont|closeGrammarModal|acceptGrammarCorrection|onSmudgeEffectsToggle|GrammarCorrector|callClaude|setAiStatus|getOptimalAnimationSettings|buildCharQueue)$',
        },
      ],
      'no-undef': 'error',
      'no-redeclare': 'warn',
      'no-constant-condition': 'warn',
      'no-empty': 'warn',
      'eqeqeq': ['warn', 'always'],
      'no-var': 'warn',
      'prefer-const': ['warn', { destructuring: 'all' }],
    },
  },
];
